server:
  error:
    include-stacktrace: on_param

# Configuração do MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true