server:
  error:
    include-stacktrace: on_param

# Configuração do MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update